#!/bin/sh

# Exit on error
set -e

REPO="https://github.com/Taum/card-repo-poc"
BRANCH_NAME="auto-update-$(date +%Y%m%d-%H%M%S)"
COMMIT_MESSAGE="Update cards via automated script"
PR_TITLE="Automated Card Update"
PR_BODY="This PR was automatically generated by the run-and-open-pr script."


run_script() {
    # $1 = root directory
    echo "Starting download script..."
    python /app/loader/altered_api_cards_dl.py "$1"
}


# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "GitHub CLI (gh) is not installed. Please install it first."
    echo "Visit: https://cli.github.com/manual/installation"
    exit 1
fi

echo "$GH_TOKEN" > /tmp/gh_token
export GH_TOKEN=

gh auth login --with-token < /tmp/gh_token

# Check if user is authenticated with GitHub
if ! gh auth status &> /dev/null; then
    echo "You are not authenticated with GitHub. Please run 'gh auth login' first."
    exit 1
fi

gh auth setup-git

git config --global user.email "brassbot@sabotageafter.rest"
git config --global user.name "Brassbot"
# git config --global 'credential.https://github.com' '!gh auth git-credential'

echo "Cloning repository: $REPO..."
# Clone the repository to a temporary directory
TEMP_DIR=$(mktemp -d)
gh repo clone "$REPO" "$TEMP_DIR"
cd "$TEMP_DIR"

# Create a new branch
echo "Creating new branch: $BRANCH_NAME..."
git checkout -b "$BRANCH_NAME"

# Run the test-loader.py script
run_script "$TEMP_DIR"

# DEBUG
exit 0



# Try to add changes
echo "Adding changes..."
git add .

# Check if there are any changes
if git diff --staged --quiet; then
    echo "No changes detected. Exiting."
    exit 0
fi

# Commit changes
echo "Committing changes..."
git commit -m "$COMMIT_MESSAGE"

# Push the branch to GitHub
echo "Pushing branch to GitHub..."
git push -u origin "$BRANCH_NAME"

# Create a pull request
echo "Creating pull request..."
gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main

echo "Done! Pull request created successfully."

